import { JSON } from "json-as/assembly";
import { EventType } from "./event";

export enum CommandName {
  Subscribe = 0,
  Unsubscribe = 1,
  SetSelectable = 2,
  GetPluginIds = 3,
  GetZellijVersion = 4,
  OpenFile = 5,
  OpenFileFloating = 6,
  OpenTerminal = 7,
  OpenTerminalFloating = 8,
  OpenCommandPane = 9,
  OpenCommandPaneFloating = 10,
  SwitchTabTo = 11,
  SetTimeout = 12,
  ExecCmd = 13,
  PostMessageTo = 14,
  PostMessageToPlugin = 15,
  HideSelf = 16,
  ShowSelf = 17,
  SwitchToMode = 18,
  NewTabsWithLayout = 19,
  NewTab = 20,
  GoToNextTab = 21,
  GoToPreviousTab = 22,
  Resize = 23,
  ResizeWithDirection = 24,
  FocusNextPane = 25,
  FocusPreviousPane = 26,
  MoveFocus = 27,
  MoveFocusOrTab = 28,
  Detach = 29,
  EditScrollback = 30,
  Write = 31,
  WriteChars = 32,
  ToggleTab = 33,
  MovePane = 34,
  MovePaneWithDirection = 35,
  ClearScreen = 36,
  ScrollUp = 37,
  ScrollDown = 38,
  ScrollToTop = 39,
  ScrollToBottom = 40,
  PageScrollUp = 41,
  PageScrollDown = 42,
  ToggleFocusFullscreen = 43,
  TogglePaneFrames = 44,
  TogglePaneEmbedOrEject = 45,
  UndoRenamePane = 46,
  CloseFocus = 47,
  ToggleActiveTabSync = 48,
  CloseFocusedTab = 49,
  UndoRenameTab = 50,
  QuitZellij = 51,
  PreviousSwapLayout = 52,
  NextSwapLayout = 53,
  GoToTabName = 54,
  FocusOrCreateTab = 55,
  GoToTab = 56,
  StartOrReloadPlugin = 57,
  CloseTerminalPane = 58,
  ClosePluginPane = 59,
  FocusTerminalPane = 60,
  FocusPluginPane = 61,
  RenameTerminalPane = 62,
  RenamePluginPane = 63,
  RenameTab = 64,
  ReportCrash = 65,
  RequestPluginPermissions = 66,
  SwitchSession = 67,
  OpenTerminalInPlace = 68,
  OpenCommandInPlace = 69,
  OpenFileInPlace = 70,
  RunCommand = 71,
  WebRequest = 72,
  DeleteDeadSession = 73,
  DeleteAllDeadSessions = 74,
  RenameSession = 75,
  UnblockCliPipeInput = 76,
  BlockCliPipeInput = 77,
  CliPipeOutput = 78,
  MessageToPlugin = 79,
}

@json
export class PluginCommand {
  name!: CommandName;
  payload!: Payload;
}

@json
export class Payload {
  subscriptions!: Array<EventType>;
}
